### ISSUE TITLE
Elasticity

### ISSUE THREAD

**Issue by SpicyMeat157** [vegapnk/RJW-Genes#170]
Few quesitons:

1-Should i apply elasticity for whole body or just gentials when using "Character Editor"?

2-My pawns lose their elasticity after a while. Is it intended or if not how can i fix it?

**Comment by vegapnk** [comment]
Thanks for reaching out @SpicyMeat157  

I am not 100% sure if there is a bug - the Elasticity Hediff comes from [LicentiaLabs](https://gitgud.io/John-the-Anabaptist/licentia-labs), I only have a Gene that adds it (and keeps it at full severity). 
So for this mod, you should (if at all) add the Gene. 

It should be at the whole body, that is the Licentia behavior too. 

Also, be a bit careful: Licentia has not been updated to RJW 5.5 as of 15.09.2024, so that might also be a source for issues.

**Comment by SpicyMeat157** [comment]
okay thanks
