### ISSUE TITLE
Shouldn't the extra breast add udder?

### ISSUE THREAD

**Issue by PKatsuwa** [vegapnk/RJW-Genes#27]
Hey guys, I'm just passing through with somewhat of a question and request of a sort.

Like the title implies shouldn't the **Extra Breasts** gene just replace the **Breasts** with the **Udder** instead of adding another **Breasts** hediff for the extra breasts? It's already there in RJW and have RimNude graphics and component already albeit assigned to another body part(Flank instead of Chest)

If not then will it becomes it's own gene at some point? Again, this is not a bug report just a question I got while I was messing around with it.

**Comment by vegapnk** [comment]
Actually, it's not that easy. It needs an upstream change in the [`RJW.Sexualizer`](https://gitgud.io/Ed86/rjw/-/blob/master/1.4/Source/Common/Helpers/Sexualizer.cs) because when I remove breasts and add udders, the sexualizer detects female pawns without breasts and gives them a fresh pair (ontop of the udders)

**Comment by vegapnk** [comment]
This hurts my brain at this point :(
