### ISSUE TITLE
Halamyr Breeder no female genitals gene issue

### ISSUE THREAD

**Issue by LimticRage** [vegapnk/RJW-Genes#49]
Even if i remove it manually after a reload the genitals are restored.
I use Menstruation and Sized apparel, don't have any issue with the eggs or gene inheritance

**Comment by vegapnk** [comment]
Thanks for reaching out ! 

Maybe a short preface why I removed the vagina: 
The basic egg mechanics from RJW are a bit flaky, and it can happen that a pawn with a non-fertilized egg gives the egg to the partner, instead of keeping it. 
This is due to how the checks are done, which in themselves are a bit complicated. 

Due to this I just removed the vagina, as this bug does not happen with the anus (to the best of my knowledge). 


To fix your issue, I might recommend making your own Xenotype for a breeder with the gene. 
Removing it from the XML is I think only an open before starting a game. You maybe can edit the save file and change the xenotype def there. 
Does that help?
